_BASE_: "../Base-DiffusionDet.yaml"
MODEL:
  META_ARCHITECTURE: 'FSDiffusionDet'
  WEIGHTS: "detectron2://benchmark_pretrained_coco/diffdet_coco_res50.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 250
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ("clipart_train2017",)
  VAL: ("clipart_test2017",)
  TEST:  ("clipart_test2017",)
SOLVER:
  STEPS: (4000,)
  MAX_ITER: 0
  BASE_LR: 5e-4
  CHECKPOINT_PERIOD: 2500
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
# TRAIN_MODE: 'support_attention'
TRAIN_MODE: 'simplefs'
FINETUNE:
  CROSS_DOMAIN: True
  MAX_ITER: 5000
  MODEL_FREEZING:
    HEAD_ALL: True
TEST:
  EVAL_PERIOD: 500
# OUTPUT_DIR: 'runs/23-01-2023_17:23:02'
# OUTPUT_DIR: 'runs/07-02-2023_17:34:01'
FEWSHOT:
  SPLIT_METHOD: 'all_novel'
  N_WAYS_TRAIN: 20
  N_WAYS_TEST: 20
  ATTENTION:
    EXTRACT_EVERY: 10
    MAX_NUM_CLASSES: 3
  K_SHOT: 10
  BASE_SUPPORT: 'rng'

